# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "db_proxy_endpoints" {
  value = module.terraform-aws-rds-proxy.db_proxy_endpoints
}

output "log_group_arn" {
  value = module.terraform-aws-rds-proxy.log_group_arn
}

output "proxy_arn" {
  value = module.terraform-aws-rds-proxy.proxy_arn
}

output "proxy_default_target_group_arn" {
  value = module.terraform-aws-rds-proxy.proxy_default_target_group_arn
}

output "proxy_default_target_group_id" {
  value = module.terraform-aws-rds-proxy.proxy_default_target_group_id
}

output "proxy_default_target_group_name" {
  value = module.terraform-aws-rds-proxy.proxy_default_target_group_name
}

output "proxy_endpoint" {
  value = module.terraform-aws-rds-proxy.proxy_endpoint
}

output "proxy_id" {
  value = module.terraform-aws-rds-proxy.proxy_id
}

output "proxy_target_endpoint" {
  value = module.terraform-aws-rds-proxy.proxy_target_endpoint
}

output "proxy_target_id" {
  value = module.terraform-aws-rds-proxy.proxy_target_id
}

output "proxy_target_port" {
  value = module.terraform-aws-rds-proxy.proxy_target_port
}

output "proxy_target_rds_resource_id" {
  value = module.terraform-aws-rds-proxy.proxy_target_rds_resource_id
}

output "proxy_target_target_arn" {
  value = module.terraform-aws-rds-proxy.proxy_target_target_arn
}

output "proxy_target_tracked_cluster_id" {
  value = module.terraform-aws-rds-proxy.proxy_target_tracked_cluster_id
}

output "proxy_target_type" {
  value = module.terraform-aws-rds-proxy.proxy_target_type
}


