# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

module "terraform-aws-rds-postgres" {
  source                              = "github.com/rhythmictech/terraform-aws-rds-postgres"
  allowed_cidr_blocks                 = local.allowed_cidr_blocks
  allowed_ipv6_cidr_blocks            = local.allowed_ipv6_cidr_blocks
  allowed_security_groups             = local.allowed_security_groups
  backup_retention_period             = local.backup_retention_period
  cloudwatch_log_exports              = local.cloudwatch_log_exports
  create_secretmanager_secret         = local.create_secretmanager_secret
  create_ssm_secret                   = local.create_ssm_secret
  database_name                       = local.database_name
  enable_deletion_protection          = local.enable_deletion_protection
  engine_version                      = local.engine_version
  final_snapshot_identifier           = local.final_snapshot_identifier
  iam_database_authentication_enabled = local.iam_database_authentication_enabled
  identifier                          = local.identifier
  identifier_prefix                   = local.identifier_prefix
  instance_class                      = local.instance_class
  monitoring_interval                 = local.monitoring_interval
  monitoring_role_arn                 = local.monitoring_role_arn
  multi_az                            = local.multi_az
  name                                = local.name
  parameter_group_family              = local.parameter_group_family
  parameters                          = local.parameters
  pass_version                        = local.pass_version
  password                            = local.password
  password_length                     = local.password_length
  performance_insights_enabled        = local.performance_insights_enabled
  port                                = local.port
  skip_final_snapshot                 = local.skip_final_snapshot
  ssm_path                            = local.ssm_path
  storage                             = local.storage
  storage_encrypted                   = local.storage_encrypted
  storage_type                        = local.storage_type
  subnet_group_name                   = local.subnet_group_name
  tags                                = local.tags
  username                            = local.username
  vpc_id                              = local.vpc_id

}
