# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "db_instance_address" {
  value = module.terraform-aws-rds.db_instance_address
}

output "db_instance_arn" {
  value = module.terraform-aws-rds.db_instance_arn
}

output "db_instance_availability_zone" {
  value = module.terraform-aws-rds.db_instance_availability_zone
}

output "db_instance_ca_cert_identifier" {
  value = module.terraform-aws-rds.db_instance_ca_cert_identifier
}

output "db_instance_cloudwatch_log_groups" {
  value = module.terraform-aws-rds.db_instance_cloudwatch_log_groups
}

output "db_instance_domain" {
  value = module.terraform-aws-rds.db_instance_domain
}

output "db_instance_domain_iam_role_name" {
  value = module.terraform-aws-rds.db_instance_domain_iam_role_name
}

output "db_instance_endpoint" {
  value = module.terraform-aws-rds.db_instance_endpoint
}

output "db_instance_engine" {
  value = module.terraform-aws-rds.db_instance_engine
}

output "db_instance_engine_version_actual" {
  value = module.terraform-aws-rds.db_instance_engine_version_actual
}

output "db_instance_hosted_zone_id" {
  value = module.terraform-aws-rds.db_instance_hosted_zone_id
}

output "db_instance_id" {
  value = module.terraform-aws-rds.db_instance_id
}

output "db_instance_name" {
  value = module.terraform-aws-rds.db_instance_name
}

output "db_instance_password" {
  value     = module.terraform-aws-rds.db_instance_password
  sensitive = true
}

output "db_instance_port" {
  value = module.terraform-aws-rds.db_instance_port
}

output "db_instance_resource_id" {
  value = module.terraform-aws-rds.db_instance_resource_id
}

output "db_instance_status" {
  value = module.terraform-aws-rds.db_instance_status
}

output "db_instance_username" {
  value     = module.terraform-aws-rds.db_instance_username
  sensitive = true
}

output "db_option_group_arn" {
  value = module.terraform-aws-rds.db_option_group_arn
}

output "db_option_group_id" {
  value = module.terraform-aws-rds.db_option_group_id
}

output "db_parameter_group_arn" {
  value = module.terraform-aws-rds.db_parameter_group_arn
}

output "db_parameter_group_id" {
  value = module.terraform-aws-rds.db_parameter_group_id
}

output "db_subnet_group_arn" {
  value = module.terraform-aws-rds.db_subnet_group_arn
}

output "db_subnet_group_id" {
  value = module.terraform-aws-rds.db_subnet_group_id
}

output "enhanced_monitoring_iam_role_arn" {
  value = module.terraform-aws-rds.enhanced_monitoring_iam_role_arn
}

output "enhanced_monitoring_iam_role_name" {
  value = module.terraform-aws-rds.enhanced_monitoring_iam_role_name
}
