# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "address" {
  value = module.terraform-aws-rds-postgres.address
}

output "instance_connection_info" {
  value = module.terraform-aws-rds-postgres.instance_connection_info
}

output "instance_id" {
  value = module.terraform-aws-rds-postgres.instance_id
}

output "password_secretsmanager_arn" {
  value = module.terraform-aws-rds-postgres.password_secretsmanager_arn
}

output "password_secretsmanager_version" {
  value = module.terraform-aws-rds-postgres.password_secretsmanager_version
}

output "password_ssm_parameter_arn" {
  value = module.terraform-aws-rds-postgres.password_ssm_parameter_arn
}

output "password_ssm_parameter_name" {
  value = module.terraform-aws-rds-postgres.password_ssm_parameter_name
}

output "password_ssm_parameter_version" {
  value = module.terraform-aws-rds-postgres.password_ssm_parameter_version
}

output "username" {
  value = module.terraform-aws-rds-postgres.username
}


