# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "subnet_ids" {
  value = module.myvpc.subnet_ids
}

output "vpc_id" {
  value = module.myvpc.vpc_id
}

output "private_web_subnets_id" {
  value = [
    aws_subnet.subnet_web_1.id,
    aws_subnet.subnet_web_2.id
  ]
}

output "private_app_subnets_id" {
  value = [
    aws_subnet.subnet_app_1.id,
    aws_subnet.subnet_app_2.id
  ]
}

output "private_db_subnets_id" {
  value = [
    aws_subnet.subnet_db_1.id,
    aws_subnet.subnet_db_2.id
  ]
}

