# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

#output "private_subnet_ids" {
#  value = module.terraform-aws-vpc.private_subnet_ids
#}

output "subnet_ids" {
  value = module.terraform-aws-vpc.subnet_ids
}

output "vpc_id" {
  value = module.terraform-aws-vpc.vpc_id
}

output "private_web_subnets" {
  value = [
    aws_subnet.subnet_web_1.id,
    aws_subnet.subnet_web_2.id
  ]
}

output "private_app_subnets" {
  value = [
    aws_subnet.subnet_app_1.id,
    aws_subnet.subnet_app_2.id
  ]
}

output "private_db_subnets" {
  value = [
    aws_subnet.subnet_db_1.id,
    aws_subnet.subnet_db_2.id
  ]
}

