# Auto-generated by fogg. Do not edit
# Make improvements in fogg, so that everyone can benefit.

output "private_subnet_ids" {
  value = module.terraform-aws-vpc.private_subnet_ids
}

output "subnet_ids" {
  value = module.terraform-aws-vpc.subnet_ids
}

output "vpc_id" {
  value = module.terraform-aws-vpc.vpc_id
}


